version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  rasa:
    build: ./rasa-chatbot
    ports:
      - "5005:5005"
    volumes:
      - ./rasa-chatbot:/app
    command: rasa run --enable-api --cors "*" --endpoints endpoints.yml

  actions:
    build: ./rasa-chatbot
    volumes:
      - ./rasa-chatbot/actions:/app/actions
    env_file:
      - ./backend/.env
    command: rasa run actions

